### ISSUE TITLE
[BUG] UndefinedError protocol String.Chars not implemented for

### ISSUE THREAD

**Issue by tcoopman** [zoedsoupe/peri#16]
This code crashes:
 ```elixir
      schema = %{
        answers: {:required, {:list, {:enum, [:string, :atom]}}}
      }

      Peri.validate(schema, %{answers: [{}]})
```

```
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for {} of type Tuple. This protocol is implemented for the following type(s): Atom, BitString, Date, DateTime, Decimal, Exqlite.Query, Float, Floki.Selector, Floki.Selector.AttributeSelector, Floki.Selector.Combinator, Floki.Selector.Functional, Floki.Selector.PseudoClass, Integer, List, NaiveDateTime, Phoenix.LiveComponent.CID, Tails, Time, URI, Uniq.UUID, Version, Version.Requirement
     code: auto_assert default_block() |> evaluate([{"1", :agree}, {"2", :disagree}])
     stacktrace:
       (elixir 1.17.3) lib/string/chars.ex:3: String.Chars.impl_for!/1
       (elixir 1.17.3) lib/string/chars.ex:22: String.Chars.to_string/1
       (peri 0.2.12) lib/peri.ex:816: Peri.validate_field/3
       (peri 0.2.12) lib/peri.ex:827: anonymous fn/4 in Peri.validate_field/3
       (elixir 1.17.3) lib/enum.ex:4858: Enumerable.List.reduce/3
       (elixir 1.17.3) lib/enum.ex:2585: Enum.reduce_while/3
       (peri 0.2.12) lib/peri.ex:826: Peri.validate_field/3
       (peri 0.2.12) lib/peri.ex:360: anonymous fn/3 in Peri.traverse_schema/3
       (stdlib 6.1.2) maps.erl:860: :maps.fold_1/4
       (peri 0.2.12) lib/peri.ex:257: Peri.validate/2
...
```

**Comment by zoedsoupe** [comment]
ok, that happens because peri is expecting a list of the enum itself, which can only be strings or atoms. i can surely make this validation, but seeing the exception that came from you test suite probably, you're trying to validate a list of tuples?

**Comment by zoedsoupe** [comment]
if yes you could do something like:
```ex
s = %{answers: {:required, {:list, {:tuple, [:string, :atom]}}}}

Peri.validate s, %{answers: [{}]}
# {:error,
#  [
#   %Peri.Error{
#     path: [:answers],
#     key: :answers,
#     content: %{length: 2, actual: 0},
#     message: "expected tuple of size 2 received tuple with 0 length",
#     errors: nil
#   }
# ]}
Peri.validate s, %{answers: [{"1", :disagree}]}
# {:ok, %{answers: [{"1", :disagree}]}}
```

since the definition

```ex
s = %{answers: {:required, {:list, {:enum, [:string, :atom]}}}}
```

expect the data to be something like

```ex
Peri.validate s, %{answers: [:string, :atom]}
# {:ok, ...}

Peri.validate s, %{answers: [:atom]}
# {:ok, ...}

Peri.validate s, %{answers: [:string]}
# {:ok, ...}
```

**Comment by zoedsoupe** [comment]
oh, forgot that enums directive should work on actually any data type... although most of my comments still valid.

until now strings values on enums are handle exactly the same as atoms, so if the enum definition is something like: `{:enum, [:green, :blue, :red]}` then `"green"` will pass successfully, which actually doesn't make quite sense, since this is a kind of type "casting", which the lib doesn't target to do

type casting is on roadmap though, so i will simplify the enum validation to only consider `val in choices`, not trying to cast any string/atom type

**Comment by zoedsoupe** [comment]
fixed on https://github.com/zoedsoupe/peri/commit/1d11647b2f6c9eae2edaf98f38b62c0131825c6b and launched new [v0.3.0](https://hexdocs.pm/peri/0.3.0)
