### ISSUE TITLE
[BUG] Using :oneof with get_schema doesn't work as expected

### ISSUE THREAD

**Issue by nickdichev-firework** [zoedsoupe/peri#5]
**Describe the bug**
I have a simple schema which uses :oneof and get_schema:

```elixir
defmodule LiveStream do
  import Peri

  defschema :agora_destination, %{
    agora_app_id: {:required, :string},
    agora_channel_name: {:required, :string},
    agora_token: {:required, :string},
    agora_user_id: {:required, :string}
  }

  defschema :rtmp_destination, %{
    rtmp_url: {:required, :string},
    stream_key: {:required, :string}
  }

  defschema :play_base_video, %{
    destination: {:oneof, [get_schema(:agora_destination), get_schema(:rtmp_destination)]}
  }
end
```

**To Reproduce**
With the above schema:

```
LiveStream.play_base_video(%{destination: %{agora_app_id: "foo", agora_channel_name: "bar", agora_token: "foo", agora_user_id: "bar"}}
{:ok,
 %{
   destination: %{
     agora_app_id: "foo",
     agora_channel_name: "bar",
     agora_token: "foo",
     agora_user_id: "bar"
   }
 }}

LiveStream.play_base_video(%{destination: %{rtmp_url: "foo", stream_key: "bar"}}
** (CaseClauseError) no case clause matching: {:error, [%Peri.Error{path: [:agora_user_id], key: :agora_user_id, content: %{}, message: "is required", errors: nil}, %Peri.Error{path: [:agora_token], key: :agora_token, content: %{}, message: "is required", errors: nil}, %Peri.Error{path: [:agora_channel_name], key: :agora_channel_name, content: %{}, message: "is required", errors: nil}, %Peri.Error{path: [:agora_app_id], key: :agora_app_id, content: %{}, message: "is required", errors: nil}]}
    (peri 0.2.6) lib/peri.ex:601: anonymous fn/4 in Peri.validate_field/3
    (elixir 1.16.2) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.2) lib/enum.ex:2582: Enum.reduce_while/3
    (peri 0.2.6) lib/peri.ex:600: Peri.validate_field/3
    (peri 0.2.6) lib/peri.ex:336: anonymous fn/3 in Peri.traverse_schema/3
    (stdlib 4.3.1.3) maps.erl:411: :maps.fold_1/3
    (peri 0.2.6) lib/peri.ex:278: Peri.validate/2
    #cell:mxydwdhm5pa27d4b:1: (file)
```

What I notice is that when I put the :rtmp_url schema first then the behavior flips, where the agora example raises and the rtmp one validates.

When I use :either instead of :oneof I get an error instead of a raise:

```
{:error,
 [
   %Peri.Error{
     path: [:destination],
     key: :destination,
     content: nil,
     message: nil,
     errors: [
       %Peri.Error{
         path: [:destination, :agora_user_id],
         key: :agora_user_id,
         content: %{},
         message: "is required",
         errors: nil
       }
     ]
   }
 ]}
```

**Expected behavior**
Both schemas are validated no matter the order specified in oneof

**Environment**
	•	Elixir version: Elixir 1.16.2 (compiled with Erlang/OTP 26)
	•	Peri version: 0.2.6

**Comment by zoedsoupe** [comment]
hi there! sorry for the late response, but i just got some time to check this issue. basically, for the `:oneof` type we loop through the possible types and try to apply it to the data, however i forgot to handle the case for nested type schemas on this cycle... i just solve it!
