### ISSUE TITLE
[BUG] A crash while validating lists

### ISSUE THREAD

**Issue by dvv** [zoedsoupe/peri#7]
**Describe the bug**
A crash while validating lists

**To Reproduce**
```ex
Peri.validate({:list, %{x: :string}}, [%{x: "X"}])
** (KeyError) key :root_data not found in: [%{x: "X"}]

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (peri 0.2.7) lib/peri.ex:672: Peri.validate_field/3
    (peri 0.2.7) lib/peri.ex:652: anonymous fn/4 in Peri.validate_field/3
    (elixir 1.17.2) lib/enum.ex:4858: Enumerable.List.reduce/3
    (elixir 1.17.2) lib/enum.ex:2585: Enum.reduce_while/3
    (peri 0.2.7) lib/peri.ex:651: Peri.validate_field/3
    (peri 0.2.7) lib/peri.ex:264: Peri.validate/2
```

**Expected behavior**
```ex
Peri.validate({:list, %{x: :string}}, [%{x: "X"}])
{:ok, [%{x: "X"}]}
```

**Comment by dvv** [comment]
Hi!
What could be the cause of:
```ex
[%Peri.Error{path: [:locks], key: :locks, content: %{type: {:list, %{object_id: {:required, :string}}}}, message: \"expected a nested schema but received schema: {:list, %{object_id: {:required, :string}}}\", errors: nil}]
```

**Comment by zoedsoupe** [comment]
what is the schema and data you're defining?

**Comment by dvv** [comment]
```ex
schema = %{approved: {:boolean, {:default, false}}, locks: {:list,
%{object_id: {:required, :string}}}, id: :uuid}

defmodule Foo.Entry do
use Ecto.Schema

schema "entry" do
field :approved, :boolean, default: false
has_many :locks, Undo.ObjectLock, foreign_key: :object_id
end
end

Peri.validate(result_schema, %Foo.Entry{approved: false, locks: []})
{:error,
 [
   %Peri.Error{
     path: [:locks],
     key: :locks,
     content: %{type: {:list, %{object_id: {:required, :string}}}},
     message: "expected a nested schema but received schema: {:list,
%{object_id: {:required, :string}}}",
     errors: nil
   }
 ]}

Peri.validate(result_schema, %{approved: false, locks: []})
{:ok, %{approved: false, locks: []}}
```

**Comment by dvv** [comment]
The strangest thing is when I remove the default:
```ex
result_schema = %{approved: :boolean, locks: {:list, %{object_id:
{:required, :string}}}, id: get_schema(:uuid)}
Peri.validate(result_schema, %Foo.Entry{approved: false, locks: []})
```
just works

**Comment by dvv** [comment]
The above example SILENTLY spoils the data in fact:
```ex
Peri.validate(result_schema, %Foo.Entry{approved: true, locks:
[%{object_id: "1"}]})
{:ok,
 %Foo.Entry{
   __meta__: #Ecto.Schema.Metadata<:built, "app", "entry">,
   id: nil,
   approved: false,
   locks: [%{object_id: "1"}]
 }}
```
Notice it resets `approved` to `false`.
I believe the problem is in how the context is transferred when diving to
nested schemas.
